### ISSUE TITLE
Random error on scalable cluster installation

### ISSUE THREAD

**Issue by 5ika** [jelastic-jps/mysql-cluster#15]
It's not always happening but I have an error while installing the auto-scale Mysql cluster into an environnement (using ON_ENV_INSTALL variable in a manifest).

```
# Checking for binary logging on master...
ERROR: Master must have binary logging turned on.
```
Sometimes, the check passes and the installation works perfectly.

I check /etc/mysql/conf.d/master.conf on the master node and `log-bin = mysql-bin` is here.
So I supposed it's a problem of ordering during installation.

**Comment by siruslan** [comment]
@5ika are using auto-cluster.jps in ON_ENV_INSTALL? or another one?
+ @sych74 for visibility.

**Comment by sych74** [comment]
The problem appears in case when master node doesn't match first.id of layer, which is possible periodically. Fix of this issue will be added now. Thank you for the cooperation.

**Comment by sych74** [comment]
Fixed!
