### ISSUE TITLE
Unable to have a functioning environment after cloning

### ISSUE THREAD

**Issue by pierre-moire** [jelastic-jps/mysql-cluster#33]
When I setup a mariaDB cluster master+master with ProxySQL and then clone the environment, the cluster is not functioning properly.

The application is unable to connect to ProxySQL, and referenced cluster nodes are the ones of the initial environment that was cloned.

Is there a way to handle this? Otherwise, can you adapt the scripts to allow cloning without additional configuration?

Thanks!

**Comment by sych74** [comment]
Hello!
Cloning support will be integrated into the JPS package in the near future.

Thanks!

**Comment by bertho-zero** [comment]
@pierre-moire I don't know if the problem you are having is the same as me but I had to add a fixed IP for ProxySQL.

Without it, I couldn't connect with the info received by email.

**Comment by sych74** [comment]
Hi, could you please describe the issue in more details? and please provide hoster where it's reproduced

**Comment by bertho-zero** [comment]
I create an environment with the default parameters, MySQL and ProxySQL, I receive the email with the login credentials to the proxy, to PhpMyAdmin and Orchestrator but if I do not manually add a fixed IP to the ProxySQL it is not possible to connect to it.

The other thing is that I can't see how the subdomain `proxy.${env.domain}:3306` (from https://github.com/jelastic-jps/mysql-cluster/blob/master/texts/proxy-entrypoint.md) is created. I imagine it is a link but I don't see it anywhere in the topology of the environment or in the links of the node.

I am at Infomaniak.

**Comment by sych74** [comment]
Entry Point for Connecting to Database Cluster via ProxySQL works only in the internal network. To connect from the outside you need to use external IP or use endpoint for connect to 3306 port.

**Comment by bertho-zero** [comment]
Thanks !

**Comment by sych74** [comment]
All custom configuration is located in `/ets/mysql/conf.d/` directory and overrides parameters from the `my.cnf.` 
The `my.cnf` contains the general configuration and uses for all DB instanses, so you can apply "Save for all instances" after changes.
