### ISSUE TITLE
MySQL - InnoDB buffer flushing

### ISSUE THREAD

**Issue by bertho-zero** [jelastic-jps/mysql-cluster#50]
Hi,

I did an installation with auto-clustering MySQL and ProxySQL with default settings. the problem is that the ram is never released even after a long time without activity, it just keeps increasing and i am forced to put low and fixed cloudlets count.

It gets expensive for not much, I have to restart MySQL servers manually from time to time.

It's the InnoDB buffer that stays full no matter what, do you have any idea how to fix this?

**Comment by sych74** [comment]
Hi @bertho-zero, unfortunately MySQL is not friendly with vertical scaling yet. But there are some workarounds for reducing memory usage:
1) [change InnoDB buffer size and make it small in the configs](https://dev.mysql.com/doc/refman/5.7/en/innodb-buffer-pool-resize.html). 
2) [change InnoDB buffer size in runtime](https://dev.mysql.com/doc/refman/5.7/en/innodb-buffer-pool-resize.html#innodb-buffer-pool-online-resize) - make it small to release RAM and then increase it again - you scan script this action.  

Please note, both workarounds may cause significant performance degradation, so do not apply it at production apps with a high load.
