### ISSUE TITLE
Firewall to allow for replication between MySQL nodes

### ISSUE THREAD

**Issue by kaore** [jelastic-jps/mysql-cluster#52]
Hi,

We are testing a mysql cluster with the objective to deploy one for our platform. We noticed that by default, firewall rules of the environment leave many ports open to "all". We disabled most of them, leaving only the ones we believe to be necessary.

In the SQL nodes section of the rules, we leave the 3306 port to the ProxySQL subgroup to let the LB nodes forward requests to the SQL nodes. Other rules are disabled. We saw that the consequence of this is that SQL nodes can no longer access each other, causing replication to break down.

Ideally, we would want to add a rule for SQL nodes to allow them to access other nodes of their own subgroup ( SQL node 1 should be able to access SQL node 2)

![image](https://user-images.githubusercontent.com/426240/91740847-296ef680-ebb4-11ea-99ef-61921682bfed.png)

The UI does not allow the submission of such a rule. Is there any other way to implement this? I find this restriction surprising as it is possible to target any other node group of the environment.

**Comment by ihorman** [comment]
Hello!  By default the nodes are not opened to "all", they are just opened to the nodes of a particular customer or to the nodes of a particular security group (more strict limitation) if such group was configured using [environment isolation feature](https://docs.jelastic.com/environment-isolation/).  Exception may be if port was opened intentionally over [Endpoints](https://docs.jelastic.com/endpoints/)  or the Public IP was attached directly to the instance, for that cases Firewall adjustments are required to make sure only appropriate IPs have direct access.

**Comment by ihorman** [comment]
Could you please clarify which provider are you using? Some of providers keep the isolation feature disabled. Do you have a requirement to isolate database layer from the application layer of the same environment?  Thanks in advance.

**Comment by kaore** [comment]
Hi, thank you for your reply. Our provider is Infomaniak. We have no specific requirements, our wish is to implement a best practice security setup. I think you are right, no public IP is attached to the instance, but if we want to explicitely list which other nodes have access to the nodes through firewall rules, we can allow nodes for another subgroup (ProxySQL for example) but not the nodes of the same. Our wish was just to have a line allowing MySQL nodes to communicate between each other through port 3306

**Comment by ihorman** [comment]
Hello! If the case is to restrict mysql nodes just to be available within the same mysql cluster you can also shift mysql cluster to a separate environment, then put that environment to a dedicated env group. That will isolate the nodes from any other nodes on a platform including those that belongs to your account too + your nodes will not require additional firewall reconfiguration after scaling-IN snd scaling-OUT actions.

**Comment by kaore** [comment]
Ok I see, thanks for your reply.
